language: node_js
node_js:
- '7'
branches:
  only:
  - src
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: KFvU8OGpI63LzZ+fM7sdQwZVHLumJt+mBI6smvIGG3E+3schhxLe6ymxcvd64NLENRiX1I8LvnIpB6ScRshiMCMxNUT0d/Yh2Fxe8n0TrBXKhkWh/uQYsBqlKO7FW0grttvq9Vhp5rmpYveF6aJFG7ThdD4IH0hPnStP7xWNuem8gRk4goaI4qIo1VuoNKiA9XI5bDj2qswLlm9LU2VFw2XMmx1efRGheM/HjLahuJkOdsBQ3HldoZfJWgvhCMqnPM1ec51puLWmlnKsu942xMZAu5fzX7zSNeGpPr94vgpp/ohRP8ePUUzoTa5YjCsSJuZZe0a3lGxfFohD04TW8F6EQ75DwGoEvy3DrRcLQdoJ/B4TChFVFGCYYfCmJJDC2t3NfFA64eh4hhApDeoB/b9FaaaVrFlmxg2njiQtQ1tnOfHyoIWTWYECJMd6iR1E96uZ2WYUkG6TQ2e4dmFLA2/eeYqmGZOUew60++u65lPhKPsXm97LusNd7D+lnNzS2S2rB9fLrru8OR6iELA9PqbY3P575ZaLpYDNw7GzwuhVlkjmUGQehUbYmB0HtZEhfOnBkn6/9R09P35E2kQdHON/CHSQqg08otdlwhrCBrQqVVOufTy/KwgLzjeUVxU3aDUASwNuBG2t1oOv8UCa7kN9GS40iejrLoa8qj1u9Yk=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
matrix:
  fast_finish: true
cache: yarn
before_install:
- yarn config set no-progress
script: yarn build
deploy:
  provider: pages
  local_dir: dist
  target_branch: master
  email: mehdi.lahlou@free.fr
  github_token: $GITHUB_TOKEN
  on:
    branch: src
  skip_cleanup: true
